name: bernardoazevedo.com.br CI
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
      - run: git pull origin main

#       - name: Deploy para minha hospedagem
#         uses: easingthemes/ssh-deploy@main
#         env:
#           SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
#           ARGS: "-rltgoDzv0 --delete"
#           SOURCE: "/"
#           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#           REMOTE_USER: ${{ secrets.REMOTE_USER }}
#           REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
#           TARGET: ${{ secrets.REMOTE_TARGET }}

#       - name: Install dependencies
#         uses: php-actions/composer@v6
#         with:
#           php_version: "8.3"
#           version: "2.5.5"

#       - name: Use Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'
#       - run: npm install
#       - run: npm run build --if-present
      # - run: npm test