name: bernardoazevedo.com.br CI
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1

      - name: Deploy para minha hospedagem
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rltgoDzv0 --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
      
      - name: Instalar composer
        shell: bash
        run: |
          source ~/.bashrc
          composer install

      - name: npm run build
        shell: bash
        run: |
          npm run build

      - name: laravel configs
        shell: bash
        run: |
          php artisan key:generate --ansi
          php artisan storage link
          ln -s public public_html